// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.budlee.httpstreaming;

public final class CalculatorOuterClass {
  private CalculatorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CalculatorRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalculatorRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double number1 = 1;</code>
     */
    double getNumber1();

    /**
     * <code>double number2 = 2;</code>
     */
    double getNumber2();

    /**
     * <code>.CalculatorRequest.OperationType operation = 3;</code>
     */
    int getOperationValue();
    /**
     * <code>.CalculatorRequest.OperationType operation = 3;</code>
     */
    com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType getOperation();

    /**
     * <code>int32 count = 4;</code>
     */
    int getCount();
  }
  /**
   * Protobuf type {@code CalculatorRequest}
   */
  public  static final class CalculatorRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CalculatorRequest)
      CalculatorRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalculatorRequest.newBuilder() to construct.
    private CalculatorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalculatorRequest() {
      number1_ = 0D;
      number2_ = 0D;
      operation_ = 0;
      count_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CalculatorRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              number1_ = input.readDouble();
              break;
            }
            case 17: {

              number2_ = input.readDouble();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              operation_ = rawValue;
              break;
            }
            case 32: {

              count_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.class, com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code CalculatorRequest.OperationType}
     */
    public enum OperationType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADD = 0;</code>
       */
      ADD(0),
      /**
       * <code>SUBTRACT = 1;</code>
       */
      SUBTRACT(1),
      /**
       * <code>MULTIPLY = 2;</code>
       */
      MULTIPLY(2),
      /**
       * <code>DIVIDE = 3;</code>
       */
      DIVIDE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ADD = 0;</code>
       */
      public static final int ADD_VALUE = 0;
      /**
       * <code>SUBTRACT = 1;</code>
       */
      public static final int SUBTRACT_VALUE = 1;
      /**
       * <code>MULTIPLY = 2;</code>
       */
      public static final int MULTIPLY_VALUE = 2;
      /**
       * <code>DIVIDE = 3;</code>
       */
      public static final int DIVIDE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OperationType valueOf(int value) {
        return forNumber(value);
      }

      public static OperationType forNumber(int value) {
        switch (value) {
          case 0: return ADD;
          case 1: return SUBTRACT;
          case 2: return MULTIPLY;
          case 3: return DIVIDE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OperationType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
              public OperationType findValueByNumber(int number) {
                return OperationType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final OperationType[] VALUES = values();

      public static OperationType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private OperationType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CalculatorRequest.OperationType)
    }

    public static final int NUMBER1_FIELD_NUMBER = 1;
    private double number1_;
    /**
     * <code>double number1 = 1;</code>
     */
    public double getNumber1() {
      return number1_;
    }

    public static final int NUMBER2_FIELD_NUMBER = 2;
    private double number2_;
    /**
     * <code>double number2 = 2;</code>
     */
    public double getNumber2() {
      return number2_;
    }

    public static final int OPERATION_FIELD_NUMBER = 3;
    private int operation_;
    /**
     * <code>.CalculatorRequest.OperationType operation = 3;</code>
     */
    public int getOperationValue() {
      return operation_;
    }
    /**
     * <code>.CalculatorRequest.OperationType operation = 3;</code>
     */
    public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType getOperation() {
      com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType result = com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType.valueOf(operation_);
      return result == null ? com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType.UNRECOGNIZED : result;
    }

    public static final int COUNT_FIELD_NUMBER = 4;
    private int count_;
    /**
     * <code>int32 count = 4;</code>
     */
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (number1_ != 0D) {
        output.writeDouble(1, number1_);
      }
      if (number2_ != 0D) {
        output.writeDouble(2, number2_);
      }
      if (operation_ != com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType.ADD.getNumber()) {
        output.writeEnum(3, operation_);
      }
      if (count_ != 0) {
        output.writeInt32(4, count_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (number1_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, number1_);
      }
      if (number2_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, number2_);
      }
      if (operation_ != com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType.ADD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, operation_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest)) {
        return super.equals(obj);
      }
      com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest other = (com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getNumber1())
          == java.lang.Double.doubleToLongBits(
              other.getNumber1()));
      result = result && (
          java.lang.Double.doubleToLongBits(getNumber2())
          == java.lang.Double.doubleToLongBits(
              other.getNumber2()));
      result = result && operation_ == other.operation_;
      result = result && (getCount()
          == other.getCount());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNumber1()));
      hash = (37 * hash) + NUMBER2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getNumber2()));
      hash = (37 * hash) + OPERATION_FIELD_NUMBER;
      hash = (53 * hash) + operation_;
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalculatorRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalculatorRequest)
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.class, com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.Builder.class);
      }

      // Construct using com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        number1_ = 0D;

        number2_ = 0D;

        operation_ = 0;

        count_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorRequest_descriptor;
      }

      public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest getDefaultInstanceForType() {
        return com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.getDefaultInstance();
      }

      public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest build() {
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest buildPartial() {
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest result = new com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest(this);
        result.number1_ = number1_;
        result.number2_ = number2_;
        result.operation_ = operation_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest) {
          return mergeFrom((com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest other) {
        if (other == com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.getDefaultInstance()) return this;
        if (other.getNumber1() != 0D) {
          setNumber1(other.getNumber1());
        }
        if (other.getNumber2() != 0D) {
          setNumber2(other.getNumber2());
        }
        if (other.operation_ != 0) {
          setOperationValue(other.getOperationValue());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double number1_ ;
      /**
       * <code>double number1 = 1;</code>
       */
      public double getNumber1() {
        return number1_;
      }
      /**
       * <code>double number1 = 1;</code>
       */
      public Builder setNumber1(double value) {
        
        number1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double number1 = 1;</code>
       */
      public Builder clearNumber1() {
        
        number1_ = 0D;
        onChanged();
        return this;
      }

      private double number2_ ;
      /**
       * <code>double number2 = 2;</code>
       */
      public double getNumber2() {
        return number2_;
      }
      /**
       * <code>double number2 = 2;</code>
       */
      public Builder setNumber2(double value) {
        
        number2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double number2 = 2;</code>
       */
      public Builder clearNumber2() {
        
        number2_ = 0D;
        onChanged();
        return this;
      }

      private int operation_ = 0;
      /**
       * <code>.CalculatorRequest.OperationType operation = 3;</code>
       */
      public int getOperationValue() {
        return operation_;
      }
      /**
       * <code>.CalculatorRequest.OperationType operation = 3;</code>
       */
      public Builder setOperationValue(int value) {
        operation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CalculatorRequest.OperationType operation = 3;</code>
       */
      public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType getOperation() {
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType result = com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType.valueOf(operation_);
        return result == null ? com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType.UNRECOGNIZED : result;
      }
      /**
       * <code>.CalculatorRequest.OperationType operation = 3;</code>
       */
      public Builder setOperation(com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest.OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CalculatorRequest.OperationType operation = 3;</code>
       */
      public Builder clearOperation() {
        
        operation_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 4;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 4;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 4;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CalculatorRequest)
    }

    // @@protoc_insertion_point(class_scope:CalculatorRequest)
    private static final com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest();
    }

    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculatorRequest>
        PARSER = new com.google.protobuf.AbstractParser<CalculatorRequest>() {
      public CalculatorRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculatorRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalculatorRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculatorRequest> getParserForType() {
      return PARSER;
    }

    public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CalculatorResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalculatorResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double result = 1;</code>
     */
    double getResult();
  }
  /**
   * Protobuf type {@code CalculatorResponse}
   */
  public  static final class CalculatorResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CalculatorResponse)
      CalculatorResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CalculatorResponse.newBuilder() to construct.
    private CalculatorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CalculatorResponse() {
      result_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CalculatorResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              result_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse.class, com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private double result_;
    /**
     * <code>double result = 1;</code>
     */
    public double getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0D) {
        output.writeDouble(1, result_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse)) {
        return super.equals(obj);
      }
      com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse other = (com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getResult())
          == java.lang.Double.doubleToLongBits(
              other.getResult()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getResult()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalculatorResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalculatorResponse)
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse.class, com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse.Builder.class);
      }

      // Construct using com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.budlee.httpstreaming.CalculatorOuterClass.internal_static_CalculatorResponse_descriptor;
      }

      public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse getDefaultInstanceForType() {
        return com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse.getDefaultInstance();
      }

      public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse build() {
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse buildPartial() {
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse result = new com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse) {
          return mergeFrom((com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse other) {
        if (other == com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse.getDefaultInstance()) return this;
        if (other.getResult() != 0D) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double result_ ;
      /**
       * <code>double result = 1;</code>
       */
      public double getResult() {
        return result_;
      }
      /**
       * <code>double result = 1;</code>
       */
      public Builder setResult(double value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CalculatorResponse)
    }

    // @@protoc_insertion_point(class_scope:CalculatorResponse)
    private static final com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse();
    }

    public static com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculatorResponse>
        PARSER = new com.google.protobuf.AbstractParser<CalculatorResponse>() {
      public CalculatorResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CalculatorResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CalculatorResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculatorResponse> getParserForType() {
      return PARSER;
    }

    public com.budlee.httpstreaming.CalculatorOuterClass.CalculatorResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatorRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculatorRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalculatorResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CalculatorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\"\273\001\n\021CalculatorRequest" +
      "\022\017\n\007number1\030\001 \001(\001\022\017\n\007number2\030\002 \001(\001\0223\n\top" +
      "eration\030\003 \001(\0162 .CalculatorRequest.Operat" +
      "ionType\022\r\n\005count\030\004 \001(\005\"@\n\rOperationType\022" +
      "\007\n\003ADD\020\000\022\014\n\010SUBTRACT\020\001\022\014\n\010MULTIPLY\020\002\022\n\n\006" +
      "DIVIDE\020\003\"$\n\022CalculatorResponse\022\016\n\006result" +
      "\030\001 \001(\0012\210\001\n\nCalculator\0226\n\tCalculate\022\022.Cal" +
      "culatorRequest\032\023.CalculatorResponse\"\000\022B\n" +
      "\023CalculaterRecursive\022\022.CalculatorRequest" +
      "\032\023.CalculatorResponse\"\0000\001B\032\n\030com.budlee." +
      "httpstreamingb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CalculatorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CalculatorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculatorRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", "Count", });
    internal_static_CalculatorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CalculatorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CalculatorResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
